"""Add vetting_status to users table

Revision ID: 45009e43b40b
Revises: 
Create Date: 2026-02-06 09:24:44.429232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45009e43b40b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vetting_status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('vetting_status')

    # ### end Alembic commands ###
